###Get all users
GET http://localhost:5000/allusers HTTP/1.1


###Update user checkInStatus
PATCH  https://checkin-app-backend.fly.dev/639c327af1f7029f2ebd29ee/true HTTP/1.1
Content-Type: application/json


###Create a user
POST  https://checkin-app-backend.fly.dev/users HTTP/1.1
Content-Type: application/json

{
    "username": "testing1",
    "password": "123"
}

###Login a user
POST  https://checkin-app-backend.fly.dev/logInUser HTTP/1.1
Content-Type: application/json

{
    "username": "j",
    "password": "j"
}